[workspace]
members = [
    "chsc",
    "test_maker",
]
resolver = "2"

package.version = "0.1.0"

[profile.release]
panic = "abort"

[profile.release-debug]
inherits = "release"
debug = true

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
